# Generated by Django 6.0.1 on 2026-01-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('smash_count', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('smash', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.pokemon')),
            ],
            options={
                'unique_together': {('username', 'pokemon')},
            },
        ),
    ]
