# Generated by Django 6.0.1 on 2026-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_stage',
            field=models.CharField(choices=[('FIRST', 'First'), ('MIDDLE', 'Middle'), ('LAST', 'Last'), ('NONE', 'No Evolution')], default='NONE', max_length=10),
        ),
    ]
