# Generated by Django 6.0.1 on 2026-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_pokemon_evolution_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
