# Generated by Django 6.0.1 on 2026-01-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_pokemon_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
